[workspace]
default-members = ["powerfmt"]
members = ["powerfmt", "powerfmt-macros"]
resolver = "2"

[workspace.dependencies]
powerfmt-macros = { version = "=0.1.0", path = "powerfmt-macros" }
syn = { version = "3.0.6", features = ["full"] }
quote = "1.0.33"
proc-macro2 = "1.0.67"

# Deny-by-default lints: These are lints that indicate a lack of compiler guarantees, future
# incompatibility (with no guarantees in the meantime) introduce surprising behavior, or are likely
# to cause undesired behavior. Code that trigger these lints should only be allowed with a
# compelling reason that is clearly documented.

# Warn-by-default lints: These are lints that indicate possible errors, future incompatibility
# (with guaranteed behavior in the meantime), or other stylistic issues (including idioms). Code
# that trigger these lints should not cause undesired behavior and may be allowed as necessary.

# All overrides need higher priority. Any overrides that are for a specific crate need to be done
# the "traditional" way of using attributes at the crate root.

[workspace.lints.rust]
ambiguous_glob_reexports = "deny"
clashing_extern_declarations = "deny"
const_item_mutation = "deny"
dangling_pointers_from_temporaries = "deny"
deref_nullptr = "deny"
drop_bounds = "deny"
future_incompatible = { level = "deny", priority = -1 }
hidden_glob_reexports = "deny"
improper_ctypes = "deny"
improper_ctypes_definitions = "deny"
invalid_from_utf8 = "deny"
invalid_macro_export_arguments = "deny"
invalid_nan_comparisons = "deny"
invalid_reference_casting = "deny"
invalid_value = "deny"
named_arguments_used_positionally = "deny"
non_ascii_idents = "deny"
opaque_hidden_inferred_bound = "deny"
overlapping_range_endpoints = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }
suspicious_double_ref_op = "deny"
unconditional_recursion = "deny"
unnameable_test_items = "deny"
unsafe_op_in_unsafe_fn = "deny"
unstable_syntax_pre_expansion = "deny"

keyword_idents = { level = "warn", priority = -1 }
let_underscore = { level = "warn", priority = -1 }
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
noop_method_call = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
unstable_name_collisions = { level = "warn", priority = 1 } # overrides #![deny(future_incompatible)]
unused = { level = "warn", priority = -1 }
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
variant_size_differences = "warn"

[workspace.lints.clippy]
alloc_instead_of_core = "deny"
std_instead_of_core = "deny"
undocumented_unsafe_blocks = "deny"

all = { level = "warn", priority = -1 }
dbg_macro = "warn"
decimal_literal_representation = "warn"
explicit_auto_deref = "warn"
get_unwrap = "warn"
manual_let_else = "warn"
missing_docs_in_private_items = "warn"
missing_enforced_import_renames = "warn"
nursery = { level = "warn", priority = -1 }
obfuscated_if_else = "warn"
print_stdout = "warn"
semicolon_outside_block = "warn"
todo = "warn"
unimplemented = "warn"
uninlined_format_args = "warn"
unnested_or_patterns = "warn"
unwrap_in_result = "warn"
unwrap_used = "warn"
use_debug = "warn"

option_if_let_else = { level = "allow", priority = 1 }     # suggests terrible code, overrides #![warn(clippy::nursery)]
redundant_pub_crate = { level = "allow", priority = 1 }    # rust-lang/rust-clippy#5369, overrides #![warn(clippy::nursery)]
uninhabited_references = { level = "allow", priority = 1 } # rust-lang/rust-clippy#11984

[workspace.lints.rustdoc]
private_doc_tests = "warn"
unescaped_backticks = "warn"
