name: "Create release"

env:
  RUSTFLAGS: -Dwarnings

concurrency:
  group: powerset-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: "0 0 * * 1" # midnight on Monday
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
  workflow_dispatch:

jobs:
  check:
    name: Type checking (${{ matrix.rust.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - { version: "1.65.0", name: MSRV }
          - { version: stable, name: stable }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust.version}}

      - name: Install cargo-hack
        shell: bash
        run: |
          curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-linux-gnu.tar.gz \
          | tar xzf - -C ~/.cargo/bin

      - name: Check feature powerset
        run: |
          cargo hack check \
          -p powerfmt \
          --no-dev-deps \
          --feature-powerset \
          --optional-deps \
          --exclude-features default

  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags') && github.run_attempt == 1
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: See the [changelog](https://github.com/jhpratt/powerfmt/blob/main/CHANGELOG.md) for details.
          prerelease: |
            ${{
              contains(github.ref, 'alpha')
              || contains(github.ref, 'beta')
              || contains(github.ref, 'rc')
            }}
